# Generated by Django 5.2.9 on 2025-12-15 18:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the alert rule', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of what this alert monitors', null=True)),
                ('metric_type', models.CharField(choices=[('error_rate', 'Error Rate'), ('latency', 'Latency'), ('token_spike', 'Token Spike')], help_text='Type of metric to monitor', max_length=50)),
                ('threshold', models.FloatField(help_text='Threshold value that triggers the alert')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this alert rule is active')),
                ('notify_email', models.BooleanField(default=False, help_text='Send email notification when triggered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, help_text='When this alert was last triggered', null=True)),
            ],
            options={
                'verbose_name': 'Alert Rule',
                'verbose_name_plural': 'Alert Rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(help_text='Alert message')),
                ('metric_value', models.FloatField(help_text='The metric value that triggered the alert')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False, help_text='Whether this alert has been acknowledged')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('alert_rule', models.ForeignKey(help_text='The alert rule that was triggered', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='llm.alertrule')),
            ],
            options={
                'verbose_name': 'Alert Log',
                'verbose_name_plural': 'Alert Logs',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='LLMRequestLog',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this request', primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, db_index=True, help_text='User identifier who made the request', max_length=255, null=True)),
                ('model_name', models.CharField(db_index=True, help_text='Name of the LLM model used', max_length=100)),
                ('prompt_text', models.TextField(help_text='The prompt sent to the LLM')),
                ('response_text', models.TextField(blank=True, help_text='The response from the LLM', null=True)),
                ('prompt_tokens', models.IntegerField(default=0, help_text='Number of tokens in the prompt')),
                ('completion_tokens', models.IntegerField(default=0, help_text='Number of tokens in the completion')),
                ('total_tokens', models.IntegerField(default=0, help_text='Total tokens used (prompt + completion)')),
                ('latency_ms', models.IntegerField(default=0, help_text='Request latency in milliseconds')),
                ('cost_estimate', models.DecimalField(decimal_places=6, default=0, help_text='Estimated cost in USD', max_digits=10)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], db_index=True, default='success', help_text='Request status', max_length=20)),
                ('error_type', models.CharField(choices=[('none', 'None'), ('timeout', 'Timeout'), ('rate_limit', 'Rate Limit'), ('invalid_prompt', 'Invalid Prompt'), ('provider_error', 'Provider Error'), ('authentication', 'Authentication Error'), ('network', 'Network Error'), ('unknown', 'Unknown Error')], db_index=True, default='none', help_text='Type of error if request failed', max_length=50)),
                ('error_message', models.TextField(blank=True, help_text='Detailed error message', null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the request was made')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional request metadata')),
            ],
            options={
                'verbose_name': 'LLM Request Log',
                'verbose_name_plural': 'LLM Request Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'status'], name='llm_llmrequ_timesta_82ffa4_idx'), models.Index(fields=['model_name', 'timestamp'], name='llm_llmrequ_model_n_b1eeb5_idx'), models.Index(fields=['error_type', 'timestamp'], name='llm_llmrequ_error_t_403285_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.CharField(choices=[('thumbs_up', 'Thumbs Up'), ('thumbs_down', 'Thumbs Down')], help_text='User rating', max_length=20)),
                ('comment', models.TextField(blank=True, help_text='Optional user comment', null=True)),
                ('user_id', models.CharField(blank=True, help_text='User who provided feedback', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When feedback was submitted')),
                ('request', models.ForeignKey(help_text='The LLM request this feedback is for', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='llm.llmrequestlog')),
            ],
            options={
                'verbose_name': 'User Feedback',
                'verbose_name_plural': 'User Feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
