# Generated by Django 5.2.9 on 2025-12-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address for OTP', max_length=254)),
                ('otp_code', models.CharField(help_text='6-digit OTP code', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0, help_text='Number of verification attempts')),
            ],
            options={
                'verbose_name': 'Email OTP',
                'verbose_name_plural': 'Email OTPs',
                'ordering': ['-created_at'],
            },
        ),
    ]
